const API_URL="https://script.google.com/macros/s/AKfycbzPmcopiDolwTWDXXtbr-UHF8ZdGibsBx07IKASCvxmKAApg5n1fFSv36wNlOQDdDsPlA/exec";
const $=s=>document.querySelector(s);let token=sessionStorage.getItem("ratu-admin-token")||"",snapshot=null;
const escapeHtml=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2800)}
async function api(payload){const response=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload),redirect:"follow"});if(!response.ok)throw new Error("Server tidak merespons");const json=await response.json();if(!json.ok)throw new Error(json.error||"Permintaan gagal");return json}
function showDashboard(){$("#login-view").hidden=true;$("#dashboard-view").hidden=false;$("#logout").hidden=false}
function showLogin(message=""){token="";sessionStorage.removeItem("ratu-admin-token");$("#dashboard-view").hidden=true;$("#login-view").hidden=false;$("#logout").hidden=true;$("#login-error").textContent=message}
$("#login-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.submitter,formEl=e.currentTarget,form=new FormData(formEl);button.disabled=true;$("#login-error").textContent="";try{const json=await api({action:"adminLogin",username:form.get("username"),password:form.get("password")});token=json.token;sessionStorage.setItem("ratu-admin-token",token);formEl.reset();showDashboard();await loadAdmin()}catch(err){$("#login-error").textContent=err.message}finally{button.disabled=false}});
$("#logout").addEventListener("click",async()=>{try{if(token)await api({action:"adminLogout",token})}catch(_){}showLogin()});
async function loadAdmin(){$("#sync-status").textContent="Memuat data terbaru…";try{const json=await api({action:"adminSnapshot",token});snapshot=json;renderStats(json);renderSettings(json.config,json.questions);renderLeaderboard(json.leaderboard);renderParticipants(json.participants);$("#sync-status").textContent=`Diperbarui ${new Date().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})}`}catch(err){if(/sesi|akses/i.test(err.message))return showLogin("Sesi berakhir. Silakan masuk kembali.");$("#sync-status").textContent="Data gagal dimuat";toast(err.message)}}
function renderStats(data){const valid=data.participants.filter(p=>p.status==="VALID"),review=data.participants.filter(p=>p.status==="REVIEW");$("#stat-total").textContent=data.participants.length;$("#stat-valid").textContent=valid.length;$("#stat-review").textContent=review.length;$("#stat-average").textContent=valid.length?Math.round(valid.reduce((n,p)=>n+p.score,0)/valid.length):0;$("#quiz-state").textContent=data.isOpen?"Sedang dibuka":"Sedang ditutup";$("#quiz-state").className=`status-chip ${data.isOpen?"open":"closed"}`}
function localDateValue(value){if(!value)return"";const d=new Date(value);if(Number.isNaN(d.getTime()))return value.slice(0,16);const pad=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function renderSettings(config,questions){const form=$("#settings-form");form.elements.week.value=config.week;form.elements.questionCount.value=config.questionCount;form.elements.openAt.value=localDateValue(config.openAt);form.elements.closeAt.value=localDateValue(config.closeAt);$("#question-editor").innerHTML=questions.map(questionCard).join("");syncQuestionCount()}
function questionCard(q={},i){const answers=q.answers||["","",""];return `<article class="question-edit" data-question><header><strong>Soal <span data-number>${i+1}</span></strong><button type="button" class="remove-question" aria-label="Hapus soal">Hapus</button></header><label>Pertanyaan<textarea data-field="text" required maxlength="300">${escapeHtml(q.text||"")}</textarea></label><div class="answer-edit">${answers.map((a,j)=>`<label><input type="radio" name="correct-${i}" value="${j}" ${Number(q.correct)===j?"checked":""} required><input data-answer="${j}" value="${escapeHtml(a)}" required maxlength="180" placeholder="Pilihan ${j+1}"></label>`).join("")}</div></article>`}
function renumber(){document.querySelectorAll("[data-question]").forEach((card,i)=>{card.querySelector("[data-number]").textContent=i+1;card.querySelectorAll('input[type="radio"]').forEach(r=>r.name=`correct-${i}`)});syncQuestionCount()}
function syncQuestionCount(){const count=document.querySelectorAll("[data-question]").length;$("#settings-form").elements.questionCount.value=count}
$("#add-question").addEventListener("click",()=>{const box=$("#question-editor"),i=box.children.length;if(i>=30)return toast("Maksimal 30 soal");box.insertAdjacentHTML("beforeend",questionCard({},i));renumber()});
$("#question-editor").addEventListener("click",e=>{const button=e.target.closest(".remove-question");if(!button)return;if(document.querySelectorAll("[data-question]").length<=1)return toast("Minimal satu soal");button.closest("[data-question]").remove();renumber()});
$("#settings-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.submitter,cards=[...document.querySelectorAll("[data-question]")];const questions=cards.map(card=>({text:card.querySelector('[data-field="text"]').value.trim(),answers:[0,1,2].map(i=>card.querySelector(`[data-answer="${i}"]`).value.trim()),correct:Number(card.querySelector('input[type="radio"]:checked').value)}));const f=e.currentTarget.elements,payload={action:"saveSettings",token,config:{week:f.week.value.trim(),questionCount:questions.length,openAt:new Date(f.openAt.value).toISOString(),closeAt:new Date(f.closeAt.value).toISOString()},questions};button.disabled=true;$("#settings-message").textContent="Menyimpan…";try{await api(payload);$("#settings-message").textContent="Pengaturan berhasil diterapkan ke laman peserta.";toast("Pengaturan tersimpan");await loadAdmin()}catch(err){$("#settings-message").textContent=err.message}finally{button.disabled=false}});
function renderLeaderboard(rows){$("#admin-leaderboard").innerHTML=rows.length?rows.map(r=>`<div class="admin-rank"><b>#${r.rank}</b><span><strong>${escapeHtml(r.name)}</strong><small>${escapeHtml(r.community)} • ${r.duration} detik</small></span><em>${r.score}</em></div>`).join(""):'<p class="empty-admin">Belum ada peserta valid.</p>'}
function renderParticipants(rows){const query=$("#participant-search").value.toLowerCase();const shown=rows.filter(r=>[r.name,r.phone,r.community,r.status].join(" ").toLowerCase().includes(query));$("#participant-body").innerHTML=shown.length?shown.map(r=>`<tr><td>${escapeHtml(new Date(r.timestamp).toLocaleString("id-ID"))}</td><td><b>${escapeHtml(r.name)}</b></td><td>${escapeHtml(r.phone)}</td><td>${escapeHtml(r.community)}</td><td><strong>${r.score}</strong></td><td>${r.duration} dtk</td><td><span class="row-status ${r.status.toLowerCase()}">${escapeHtml(r.status)}</span></td></tr>`).join(""):'<tr><td colspan="7" class="empty-admin">Data tidak ditemukan.</td></tr>'}
$("#participant-search").addEventListener("input",()=>snapshot&&renderParticipants(snapshot.participants));$("#refresh-admin").addEventListener("click",loadAdmin);if(token){showDashboard();loadAdmin()}else showLogin();
