const API_URL="https://script.google.com/macros/s/AKfycbzPmcopiDolwTWDXXtbr-UHF8ZdGibsBx07IKASCvxmKAApg5n1fFSv36wNlOQDdDsPlA/exec";
const TOKEN_KEY="ratu-profile-token",LEGACY_KEY="ratu-finance-records-v1";
const $=selector=>document.querySelector(selector);
const parseAmount=value=>Number(String(value||"").replace(/\D/g,""));
const money=value=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value);
const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const today=new Date(),currentMonth=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}`;
let token=readToken(),records=[];

function readToken(){try{return localStorage.getItem(TOKEN_KEY)||""}catch(_){return""}}
function storeToken(value){try{value?localStorage.setItem(TOKEN_KEY,value):localStorage.removeItem(TOKEN_KEY)}catch(_){}}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2800)}
async function api(payload){const response=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload),redirect:"follow"});if(!response.ok)throw new Error("Server tidak merespons");const json=await response.json();if(!json.ok)throw new Error(json.error||"Permintaan gagal");return json}
function setBusy(form,busy){form.querySelectorAll("input,select,button").forEach(el=>el.disabled=busy)}
function showGate(message=""){token="";storeToken("");records=[];$("#finance-app").hidden=true;$("#profile-gate").hidden=false;$("#header-action").href="index.html#kuis";$("#header-action").textContent="Ikut Kuis";$("#profile-error").textContent=message}
function showApp(profile){$("#profile-gate").hidden=true;$("#finance-app").hidden=false;$("#profile-name").textContent=profile.name;$("#profile-phone").textContent=`WhatsApp ${profile.phone}`;$("#header-action").href="#form-catatan";$("#header-action").textContent="Tambah Catatan"}

$("#finance-form").elements.date.value=today.toISOString().slice(0,10);$("#month-filter").value=currentMonth;
const amountInput=$("#finance-form").elements.amount;amountInput.addEventListener("input",()=>{const digits=String(amountInput.value).replace(/\D/g,"").slice(0,13);amountInput.value=digits?new Intl.NumberFormat("id-ID").format(Number(digits)):""});
$("#profile-login-form").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form);setBusy(form,true);$("#profile-error").textContent="Memeriksa profil…";try{const json=await api({action:"profileLogin",phone:data.get("phone"),pin:data.get("pin")});token=json.profileToken;storeToken(token);form.reset();showApp(json.profile);await loadRecords();await migrateLegacy()}catch(error){$("#profile-error").textContent=error.message}finally{setBusy(form,false)}});
$("#profile-logout").addEventListener("click",async()=>{const old=token;showGate();try{await api({action:"profileLogout",profileToken:old})}catch(_){}toast("Ibu sudah keluar dari profil")});

async function restoreSession(){if(!token)return showGate();try{const json=await api({action:"profileMe",profileToken:token});showApp(json.profile);await loadRecords();await migrateLegacy()}catch(_){showGate("Sesi telah berakhir. Silakan masuk kembali.")}}
async function loadRecords(){const json=await api({action:"financeList",profileToken:token});records=Array.isArray(json.records)?json.records.filter(validRecord):[];render()}
function validRecord(record){return record&&typeof record.id==="string"&&["income","expense"].includes(record.type)&&Number.isFinite(Number(record.amount))&&/^\d{4}-\d{2}-\d{2}$/.test(record.date)}

$("#finance-form").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),button=event.submitter,payload={action:"financeAdd",profileToken:token,type:data.get("type"),amount:parseAmount(data.get("amount")),date:data.get("date"),category:data.get("category"),note:String(data.get("note")||"").trim()};button.disabled=true;$("#finance-message").textContent="Menyimpan dengan aman…";try{const json=await api(payload);records.unshift(json.record);form.reset();form.elements.type.value="expense";form.elements.date.value=new Date().toISOString().slice(0,10);$("#finance-message").textContent="Catatan berhasil disimpan.";render();$("#finance-history").scrollIntoView({behavior:"smooth",block:"center"})}catch(error){if(/sesi profil/i.test(error.message))return showGate("Sesi berakhir. Silakan masuk kembali.");$("#finance-message").textContent=error.message}finally{button.disabled=false}});
$("#month-filter").addEventListener("change",render);
$("#finance-history").addEventListener("click",async event=>{const button=event.target.closest("[data-delete]");if(!button||button.disabled)return;if(!confirm("Hapus catatan ini, Bu?"))return;button.disabled=true;try{await api({action:"financeDelete",profileToken:token,transactionId:button.dataset.delete});records=records.filter(record=>record.id!==button.dataset.delete);render();toast("Catatan dihapus")}catch(error){button.disabled=false;if(/sesi profil/i.test(error.message))return showGate("Sesi berakhir. Silakan masuk kembali.");toast(error.message)}});

async function migrateLegacy(){let legacy=[];try{const parsed=JSON.parse(localStorage.getItem(LEGACY_KEY)||"[]");legacy=Array.isArray(parsed)?parsed.filter(validRecord):[]}catch(_){}if(!legacy.length)return;let completed=0;for(const item of legacy){try{await api({action:"financeAdd",profileToken:token,requestId:`legacy-${item.id}`,type:item.type,amount:Number(item.amount),date:item.date,category:item.category,note:item.note||""});completed++}catch(_){break}}if(completed===legacy.length){try{localStorage.removeItem(LEGACY_KEY)}catch(_){}await loadRecords();toast(`${completed} catatan lama berhasil dipindahkan ke profil Ibu`)}}

function render(){
  const selected=$("#month-filter").value||currentMonth,rows=records.filter(record=>record.date.startsWith(selected)),income=rows.filter(record=>record.type==="income").reduce((sum,record)=>sum+Number(record.amount),0),expense=rows.filter(record=>record.type==="expense").reduce((sum,record)=>sum+Number(record.amount),0),balance=income-expense,rate=income>0?Math.max(-100,Math.min(100,Math.round(balance/income*100))):0;
  $("#total-income").textContent=money(income);$("#total-expense").textContent=money(expense);$("#total-balance").textContent=money(balance);$("#total-balance").classList.toggle("negative",balance<0);$("#balance-label").textContent=balance<0?"Pengeluaran melebihi pemasukan":balance>0?"Masih ada ruang untuk ditabung":"Mulai dari satu catatan";$("#saving-rate").textContent=`${rate}%`;$("#saving-progress").value=Math.max(0,rate);
  const categories={};rows.filter(record=>record.type==="expense").forEach(record=>categories[record.category]=(categories[record.category]||0)+Number(record.amount));const top=Object.entries(categories).sort((a,b)=>b[1]-a[1])[0];$("#top-category").textContent=top?`${top[0]} • ${money(top[1])}`:"Belum ada";
  let insight="Tambahkan pemasukan dan pengeluaran agar RATU dapat membantu membaca kondisi bulan ini.";if(income&&expense===0)insight="Pemasukan sudah tercatat. Jangan lupa catat pengeluaran supaya ringkasannya lebih akurat.";else if(balance<0)insight="Pengeluaran lebih besar dari pemasukan. Coba periksa kategori terbesar dan pilih satu belanja yang dapat dikurangi.";else if(rate>=20)insight="Bagus, Bu! Lebih dari 20% pemasukan masih tersisa. Pertimbangkan memisahkannya untuk tabungan atau dana darurat.";else if(balance>0)insight="Keuangan masih positif. Sisihkan sebagian sisa uang sebelum dipakai untuk kebutuhan lain.";$("#financial-insight p").textContent=insight;
  $("#finance-history").innerHTML=rows.length?[...rows].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(record=>`<article class="transaction-row"><span class="transaction-icon ${record.type}">${record.type==="income"?"↓":"↑"}</span><span><b>${esc(record.note||record.category)}</b><small>${esc(record.category)} • ${new Date(record.date+"T00:00:00").toLocaleDateString("id-ID",{day:"numeric",month:"short",year:"numeric"})}</small></span><strong class="${record.type}">${record.type==="income"?"+":"−"}${money(record.amount)}</strong><button type="button" data-delete="${esc(record.id)}" aria-label="Hapus catatan ${esc(record.note||record.category)}">×</button></article>`).join(""):'<div class="finance-empty"><span>📝</span><b>Belum ada catatan bulan ini</b><p>Catatan yang Ibu tambahkan akan muncul di sini.</p></div>';
}

restoreSession();
